### ISSUE TITLE
Generate new keys for other languages

### ISSUE THREAD

**Issue by vanlooverenkoen** [vanlooverenkoen/locale_gen#3]
Add the option to automaticly generate the new keys for the other languages

**Comment by NicolaVerbeeck** [comment]
What do you mean?

**Comment by vanlooverenkoen** [comment]
This is for local support.
So typically you would populate 1 language with all your keys & translations.

It would be nice if we could run something that generated the missing keys in the other translation files as well.

en:
```
{
   "title":"Hi",
   "title2":"Hi2",
   "title3":"Hi3",
}
```

nl:
```
{
   "title":"Hallo",
}
```

after generating the missing keys nl would look like this:

nl:
```
{
   "title":"Hallo",
   "title2":"",
   "title3":"",
}
```

**Comment by NicolaVerbeeck** [comment]
Since we don't generate the json files in this package, this would be strange, no?

**Comment by vanlooverenkoen** [comment]
this package generates dart files from your json files. Because this package is for local support it would be nice to have the other way around implemented as well. But this is not a high prio.

**Comment by NicolaVerbeeck** [comment]
I disagree, this would create a flip-flop battle between whatever creates your json files and this package. Stick to your responsibility and have the json generators take care of this

**Comment by vanlooverenkoen** [comment]
Alright I will move that to another package in the future
