### ISSUE TITLE
Add support for country codes + language

### ISSUE THREAD

**Issue by vanlooverenkoen** [vanlooverenkoen/locale_gen#45]
`Locale('nl')` is supported

`Locale('nl_BE')` is not

This should move to something like this:
`Locale.fromSubtags(languageCode: ‘zh’, scriptCode: ‘Hant’, countryCode: ‘TW’)`

**Comment by NicolaVerbeeck** [comment]
Fixed in #50

**Comment by vanlooverenkoen** [comment]
Fixed in 3.4.0
